# .streamlit/secrets.toml
OPENAI_API_KEY = "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"
LANGFUSE_SECRET_KEY = "sk-lf-221d510b-695e-46dc-8e03-8b2f6f41e0f4"
LANGFUSE_PUBLIC_KEY = "pk-lf-1323a43b-754e-4335-a7c7-63d40429917b"
LANGFUSE_HOST = "https://cloud.langfuse.com"