# .streamlit/secrets.toml

LANGFUSE_SECRET_KEY = "sk-lf-221d510b-695e-46dc-8e03-8b2f6f41e0f4"
LANGFUSE_PUBLIC_KEY = "pk-lf-1323a43b-754e-4335-a7c7-63d40429917b"
LANGFUSE_HOST = "https://cloud.langfuse.com"